2024-03-11 12:54:36,142 INFO    MainThread:2204262 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-11 12:54:36,143 INFO    MainThread:2204262 [wandb_setup.py:_flush():76] Configure stats pid to 2204262
2024-03-11 12:54:36,143 INFO    MainThread:2204262 [wandb_setup.py:_flush():76] Loading settings from /home/sagar/.config/wandb/settings
2024-03-11 12:54:36,143 INFO    MainThread:2204262 [wandb_setup.py:_flush():76] Loading settings from /home/sagar/trans-fer-entropy/article_filtering/wandb/settings
2024-03-11 12:54:36,143 INFO    MainThread:2204262 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'notebook_name': '/home/sagar/trans-fer-entropy/article_filtering/01-sk-filter_testing.ipynb'}
2024-03-11 12:54:36,143 INFO    MainThread:2204262 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-11 12:54:36,143 INFO    MainThread:2204262 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-11 12:54:36,143 INFO    MainThread:2204262 [wandb_init.py:_log_setup():526] Logging user logs to /home/sagar/trans-fer-entropy/article_filtering/wandb/run-20240311_125436-g2s6yusy/logs/debug.log
2024-03-11 12:54:36,143 INFO    MainThread:2204262 [wandb_init.py:_log_setup():527] Logging internal logs to /home/sagar/trans-fer-entropy/article_filtering/wandb/run-20240311_125436-g2s6yusy/logs/debug-internal.log
2024-03-11 12:54:36,143 INFO    MainThread:2204262 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fa280bde3d0>
2024-03-11 12:54:36,144 INFO    MainThread:2204262 [wandb_init.py:init():566] calling init triggers
2024-03-11 12:54:36,144 INFO    MainThread:2204262 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-11 12:54:36,144 INFO    MainThread:2204262 [wandb_init.py:init():616] starting backend
2024-03-11 12:54:36,144 INFO    MainThread:2204262 [wandb_init.py:init():620] setting up manager
2024-03-11 12:54:36,145 INFO    MainThread:2204262 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-11 12:54:36,146 INFO    MainThread:2204262 [wandb_init.py:init():628] backend started and connected
2024-03-11 12:54:36,158 INFO    MainThread:2204262 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-11 12:54:36,162 INFO    MainThread:2204262 [wandb_init.py:init():720] updated telemetry
2024-03-11 12:54:36,169 INFO    MainThread:2204262 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-11 12:54:36,415 INFO    MainThread:2204262 [wandb_run.py:_on_init():2262] communicating current version
2024-03-11 12:54:36,462 INFO    MainThread:2204262 [wandb_run.py:_on_init():2271] got version response upgrade_message: "wandb version 0.16.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-03-11 12:54:36,462 INFO    MainThread:2204262 [wandb_init.py:init():804] starting run threads in backend
2024-03-11 12:54:42,623 INFO    MainThread:2204262 [wandb_run.py:_console_start():2241] atexit reg
2024-03-11 12:54:42,623 INFO    MainThread:2204262 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-11 12:54:42,623 INFO    MainThread:2204262 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-11 12:54:42,623 INFO    MainThread:2204262 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-11 12:54:42,624 INFO    MainThread:2204262 [wandb_init.py:init():847] run started, returning control to user process
2024-03-11 12:54:42,625 INFO    MainThread:2204262 [wandb_watch.py:watch():51] Watching
2024-03-11 12:54:44,241 INFO    MainThread:2204262 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-11 12:54:44,241 INFO    MainThread:2204262 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-11 12:55:15,966 INFO    MainThread:2204262 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-11 12:55:15,985 INFO    MainThread:2204262 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-11 12:55:15,985 INFO    MainThread:2204262 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-11 12:55:19,141 INFO    MainThread:2204262 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-11 12:55:23,627 INFO    MainThread:2204262 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-11 12:55:23,628 INFO    MainThread:2204262 [wandb_setup.py:_flush():76] Configure stats pid to 2204262
2024-03-11 12:55:23,628 INFO    MainThread:2204262 [wandb_setup.py:_flush():76] Loading settings from /home/sagar/.config/wandb/settings
2024-03-11 12:55:23,628 INFO    MainThread:2204262 [wandb_setup.py:_flush():76] Loading settings from /home/sagar/trans-fer-entropy/article_filtering/wandb/settings
2024-03-11 12:55:23,628 INFO    MainThread:2204262 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'notebook_name': '/home/sagar/trans-fer-entropy/article_filtering/01-sk-filter_testing.ipynb'}
2024-03-11 12:55:23,628 INFO    MainThread:2204262 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-11 12:55:23,628 INFO    MainThread:2204262 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-11 12:55:23,628 INFO    MainThread:2204262 [wandb_init.py:_log_setup():526] Logging user logs to /home/sagar/trans-fer-entropy/article_filtering/wandb/run-20240311_125523-xmc0ijs5/logs/debug.log
2024-03-11 12:55:23,628 INFO    MainThread:2204262 [wandb_init.py:_log_setup():527] Logging internal logs to /home/sagar/trans-fer-entropy/article_filtering/wandb/run-20240311_125523-xmc0ijs5/logs/debug-internal.log
2024-03-11 12:55:23,629 INFO    MainThread:2204262 [wandb_init.py:init():566] calling init triggers
2024-03-11 12:55:23,629 INFO    MainThread:2204262 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-11 12:55:23,629 INFO    MainThread:2204262 [wandb_init.py:init():591] re-initializing run, found existing run on stack: g2s6yusy
2024-03-11 12:55:23,631 INFO    MainThread:2204262 [wandb_run.py:_finish():1970] finishing run sagarkumar/few_shot_1/g2s6yusy
2024-03-11 12:55:23,678 INFO    MainThread:2204262 [jupyter.py:save_history():445] not saving jupyter history
2024-03-11 12:55:23,678 INFO    MainThread:2204262 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-11 12:55:23,678 INFO    MainThread:2204262 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-11 12:55:23,678 INFO    MainThread:2204262 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-11 12:55:23,678 INFO    MainThread:2204262 [wandb_run.py:_restore():2193] restore
2024-03-11 12:55:23,678 INFO    MainThread:2204262 [wandb_run.py:_restore():2199] restore done
2024-03-11 12:55:29,060 INFO    MainThread:2204262 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-11 12:55:29,060 INFO    MainThread:2204262 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-11 12:55:29,069 INFO    MainThread:2204262 [wandb_run.py:_footer_sync_info():3825] logging synced files
